### ISSUE TITLE
Add pipeline to publish docker images to Docker Hub

### ISSUE THREAD

**Issue by pawisoon** [bndw/len.to#34]
Hi, 
I love the project and would like to self-host it. 
Will you be able to create a docker image and publish to hub.docker.com  ? Or add a pipeline that builds and publishes the image when the repo has a new release? 

Cheers,
P

**Comment by bndw** [comment]
Hi, there is already a pipeline that publishes a docker image to dockerhub.
https://github.com/bndw/len.to/blob/master/.github/workflows/master_push.yml
